import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

let birds = [
  {
    name: "blue jay",
    color: "blue",
    region: "north america",
  },
  {
    name: "sun conure",
    color: "orange",
    region: "south america",
  },
  {
    name: "house sparrow",
    color: "brown",
    region: "north america",
  },
  {
    name: "bald eagle",
    color: "brown",
    region: "north america",
  },
  {
    name: "cockatiel",
    color: "varies",
    region: "australia",
  },
];
birds.sort((a, b) => a.name.localeCompare(b.name));
function ShowBirdList() {
  return birds.map((bird, i) => (
    <div key={i} className="birdDiv">
      <ul>
        <li>Name: {bird.name}</li>
        <li>Color: {bird.color}</li>
        <li>Region: {bird.region}</li>
      </ul>
    </div>
  ));
}

export default function MyApp() {
  const [message, setMessage] = useState("");
  const [birdName, setBirdName] = useState("");
  const [birdColor, setBirdColor] = useState("");
  const [birdRegion, setBirdRegion] = useState("");

  const handleAddBird = (event) => {
    event.preventDefault();
    const newBird = {
      name: birdName,
      color: birdColor,
      region: birdRegion,
    };
    birds.push(newBird);
    setBirdName("");
    setBirdColor("");
    setBirdRegion("");
    console.log(birds);
  };

  return (
    <>
      <Head>
        <title>JimeBird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="back">
        <div className="mainPage">
          <h1>Hi, Welcome to Jimmy's Bird database</h1>
          <p>
            This will be a database of birds that Jimmy can name off the top of
            his head.
          </p>
        </div>

        <div className="birdSearch">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (
                birds.filter(
                  (bird) => bird.name === e.target[0].value.toLowerCase()
                ).length > 0
              ) {
                setMessage("Bird found");

                console.log(
                  birds.filter(
                    (bird) => bird.name === e.target[0].value.toLowerCase()
                  )
                );
              } else {
                setMessage("Bird not found");
              }
            }}
          >
            <input className="searchForm" type="text" placeholder="Search" />
            <button type="submit">Search</button>
          </form>
        </div>

        <p>{message}</p>
        <div className="addBird">
          <form onSubmit={handleAddBird}>
            <input
              type="text"
              placeholder="Name"
              value={birdName}
              onChange={(e) => setBirdName(e.target.value)}
            />
            <input
              type="text"
              placeholder="Color"
              value={birdColor}
              onChange={(e) => setBirdColor(e.target.value)}
            />
            <input
              type="text"
              placeholder="Region"
              value={birdRegion}
              onChange={(e) => setBirdRegion(e.target.value)}
            />
            <button type="submit">Add</button>
          </form>
          <Link href="/bird-catalog">
            <button id="catalogButton">Go to Jimmy's Bird Catalog</button>
          </Link>
          <br />
          <ShowBirdList />
        </div>
      </div>
    </>
  );
}
