import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { birds } from "./bird-catalog";

// BirdComponent to display the bird details
const BirdComponent = ({ bird }) => {
  return (
    <div>
      <ul>
        <li>Name: {bird.name}</li>
        <li>Color: {bird.color}</li>
        <li>Region: {bird.region}</li>
      </ul>
    </div>
  );
};

export default function MyApp() {
  const [message, setMessage] = useState("");
  const [foundBird, setFoundBird] = useState(null);

  const handleSearch = (e) => {
    e.preventDefault();
    const searchValue = e.target[0].value.toLowerCase();
    const foundBird = birds.find((bird) => bird.name === searchValue);

    if (foundBird) {
      setMessage("Bird found");
      setFoundBird(foundBird);
      console.log(foundBird);
    } else {
      setMessage("Bird not found");
      setFoundBird(null);
    }
  };

  return (
    <>
      <Head>
        <title>JimeBird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="back">
        <div className="mainPage">
          <h1>Hi, Welcome to Jimmy's Bird database</h1>
          <p>
            This will be a database of birds that Jimmy can name off the top of
            his head.
          </p>
        </div>

        <div className="birdSearch">
          <form onSubmit={handleSearch}>
            <input className="searchForm" type="text" placeholder="Search" />
            <button type="submit">Search</button>
          </form>
          <p>{message}</p>
          {foundBird && <BirdComponent bird={foundBird} />}
        </div>

        <Link href="/bird-catalog">
          <button id="catalogButton">Go to Jimmy's Bird Catalog</button>
        </Link>
        <br />
      </div>
    </>
  );
}
