import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import { db } from "../../lib/firebase";
import { collection, getDocs } from "firebase/firestore";

// BirdComponent to display the bird details
const BirdComponent = ({ bird }) => (
  <div>
    <ul>
      <li>Name: {bird.name}</li>
      <li>Color: {bird.color}</li>
      <li>Region: {bird.region}</li>
    </ul>
  </div>
);

export default function MyApp() {
  const [message, setMessage] = useState("");
  const [foundBird, setFoundBird] = useState(null);
  const [birds, setBirds] = useState([]); // Initialize as empty array

  // Fetch birds from Firestore
  useEffect(() => {
    const fetchBirds = async () => {
      const querySnapshot = await getDocs(collection(db, "birds"));
      const birdList = querySnapshot.docs.map((doc) => doc.data()); // Get bird objects
      setBirds(birdList); // Set state
    };

    fetchBirds();
  }, []);

  const handleSearch = (e) => {
    e.preventDefault();
    const searchValue = e.target[0].value.toLowerCase();

    // Ensure birds is loaded before searching
    if (!birds.length) {
      setMessage("No birds available to search.");
      return;
    }

    const foundBird = birds.find(
      (bird) => bird.name.toLowerCase() === searchValue
    );

    if (foundBird) {
      setMessage("Bird found");
      setFoundBird(foundBird);
      console.log(foundBird);
    } else {
      setMessage("Bird not found");
      setFoundBird(null);
    }
  };

  return (
    <>
      <Head>
        <title>JimeBird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="centerplease">
        <img className="logoImage" src="png/logo-color.png" />
      </div>

      <div className="back">
        <div className="mainPage">
          <h1>Hi, Welcome to Jimmy's Bird Database</h1>
          <p>
            This will be a database of birds that Jimmy can name off the top of
            his head.
          </p>
        </div>

        <div className="birdSearch">
          <form onSubmit={handleSearch}>
            <input className="searchForm" type="text" placeholder="Search" />
            <button className="searchButton" type="submit">
              Search
            </button>
          </form>
          <p>{message}</p>
          {foundBird && <BirdComponent bird={foundBird} />}
        </div>

        <Link href="/bird-catalog">
          <button className="catalogButton">Go to Jimmy's Bird Catalog</button>
        </Link>
        <br />
      </div>
    </>
  );
}
